services:
    db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=fridge_user
            - POSTGRES_PASSWORD=fridge_password
            - POSTGRES_DB=fridge_db
        ports:
            - "5432:5432"
    server:
        build:
            context: backend
        ports:
            - "8000:8080"
        depends_on:
            - db
        environment:
            - DATABASE_URL=postgresql://fridge_user:fridge_password@db:5432/fridge_db

    client:
        build:
            context: frontend
        ports:
            - "3000:80"
        depends_on:
            - server
        environment:
            - VITE_BACKEND_URL=http://0.0.0.0:8080
